return {
  ui = {
    BigCircle = "ﱣ ",
    BigUnfilledCircle = " ",
    BookMark = " ",
    Bug = " ",
    Calendar = " ",
    Check = " ",
    ChevronRight = ">",
    Circle = " ",
    Close = " ",
    Code = " ",
    Comment = " ",
    Dashboard = "﵁ ",
    Fire = " ",
    Gear = " ",
    History = " ",
    Lightbulb = "ﯧ ",
    List = " ",
    Lock = " ",
    NewFile = " ",
    Note = " ",
    Package = " ",
    Pencil = " ",
    Project = " ",
    Search = " ",
    SignIn = " ",
    Table = " ",
    Telescope = " ",
  },
  diagnostics = {
    Error = " ",
    Hint = "כֿ ",
    Information = " ",
    Question = " ",
    Warning = " ",
  },
  lsp = {
    server_installed = "✓",
    server_pending = "➜",
    server_uninstalled = "✗",
  },
  git = {
    Add = " ",
    Diff = "繁 ",
    Ignore = " ",
    Mod = " ",
    Remove = " ",
    Rename = "凜 ",
    Repo = " ",
  },
}
